name: Test and coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Test pkg1
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd pkg1 && go test -coverprofile=coverage1.out -covermode=atomic ./... && goveralls -coverprofile=coverage1.out -service=github -reponame=mono && cd ..
      - name: Test pkg2
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd pkg2 && go test -coverprofile=coverage2.out -covermode=atomic ./... && goveralls -coverprofile=coverage2.out -service=github -reponame=mono && cd ..